services:
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yaml
  
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./config.yml:/etc/promtail/config.yml
      - /Users/sunil/Library/Logs/DiagnosticReports/:/var/log/mac:/var/log/mac  

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
